name: docker

on:
  push:
    branches:
      - 'develop'
    tags:
      - 'v*'
env:
  DOCKERHUB_TAG: ${{ github.ref_name == 'main' && 'latest' || 'develop' }}      

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true          
    
      - 
        id: container_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}/${{ github.event.repository.name }}
      
      - 
        name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ steps.container_name.outputs.lowercase }}
          tags: |
            type=semver,pattern={{version}}
      
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ github.ref_name == 'develop' && format('{0}:{1}', steps.container_name.outputs.lowercase, env.DOCKERHUB_TAG) || '' }}

